const status=document.getElementById('client-status');
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
async function api(path='',data){const headers={Authorization:'Bearer '+token};if(data)headers['Content-Type']='application/json';const response=await fetch('/api/client'+path,{method:data?'POST':'GET',headers,...(data?{body:JSON.stringify(data)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;}
function privateLink(id,url){const el=document.getElementById(id);el.hidden=true;if(!url)return;try{const link=new URL(url);if(link.protocol!=='https:')return;el.href=link.href;el.hidden=false;}catch{}}
async function load(){try{const data=await api();document.getElementById('client-content').hidden=false;status.textContent=`${data.package} — ${new Date(data.start*1000).toLocaleString('en-US',{timeZone:'America/Chicago'})} (America/Chicago). Deposit verified.`;document.getElementById('client-package').value=data.package;const form=document.getElementById('intake-form');form.elements.portfolioPermission.checked=data.consent;if(data.intake){for(const [key,value] of Object.entries(data.intake))if(form.elements[key])form.elements[key].value=value;}else{form.elements.name.value=data.name;form.elements.email.value=data.email;}
 const select=document.getElementById('consult-slot');select.replaceChildren(new Option(data.consult?'Consultation already scheduled':data.intake?'Choose an open phone call':'Save intake to see phone call availability',''));for(const slot of data.slots)select.append(new Option(new Date(slot.start*1000).toLocaleString('en-US',{timeZone:'America/Chicago'}),slot.id));document.querySelector('#consult-form button').disabled=!!data.consult||!data.slots.length;
 document.getElementById('delivery-info').textContent=`Remaining balance: $${data.balance}${data.balancePaid?' — verified paid':''}. Your package includes ${data.package.startsWith('Essential')?3:5} edited JPEGs.`;document.getElementById('balance').disabled=data.balancePaid;privateLink('proof-link',data.proofUrl);privateLink('delivery-link',data.deliveryUrl);document.querySelector('#selection-form button').disabled=!data.proofUrl;
 }catch(e){status.textContent=e.message;document.getElementById('client-content').hidden=true;}}
async function save(path,data){try{await api(path,data);await load();status.textContent+=' Saved.';}catch(e){status.textContent=e.message;}}
document.getElementById('intake-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.portfolioPermission=e.target.elements.portfolioPermission.checked;save('/intake',data);};
document.getElementById('consult-form').onsubmit=e=>{e.preventDefault();save('/consult',Object.fromEntries(new FormData(e.target)));};
document.getElementById('selection-form').onsubmit=e=>{e.preventDefault();save('/selection',Object.fromEntries(new FormData(e.target)));};
document.getElementById('balance').onclick=async()=>{try{const data=await api('/balance',{});const url=new URL(data.url);if(url.protocol!=='https:'||url.hostname!=='checkout.stripe.com')throw new Error('Checkout unavailable');location.assign(url.href);}catch(e){status.textContent=e.message;}};
load();

