import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {PACKAGES,chicagoEpoch,weekOf,paidSessionMatches,cryptToken,digest} from '../src/domain.mjs';
import {handle,processPaid} from '../src/api.mjs';
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001_booking.sql',import.meta.url),'utf8'));db.exec(readFileSync(new URL('../migrations/0002_terms.sql',import.meta.url),'utf8'));db.exec(readFileSync(new URL('../migrations/0003_protect_closed_slots.sql',import.meta.url),'utf8'));return db;}
function adapter(db){return {prepare(sql){let args=[];const prepared={bind(...values){args=values;return prepared;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return db.prepare(sql).run(...args);}};return prepared;},async batch(statements){db.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}};}
function seed(db,limit=6){db.prepare('INSERT INTO weeks VALUES(?,?)').run('2027-01-04',limit);db.prepare('INSERT INTO blocks VALUES(?,?,?,?,?)').run('b1','b4us',chicagoEpoch('2027-01-04T09:00'),chicagoEpoch('2027-01-04T12:00'),'2027-01-04');db.prepare('INSERT INTO blocks VALUES(?,?,?,?,?)').run('b2','b4us',chicagoEpoch('2027-01-05T09:00'),chicagoEpoch('2027-01-05T12:00'),'2027-01-04');}
function slot(db,id,start='2027-01-06T12:00',kind='shoot',minutes=60){const epoch=chicagoEpoch(start);db.prepare('INSERT INTO slots(id,kind,start,end,week,local_date) VALUES(?,?,?,?,?,?)').run(id,kind,epoch,epoch+minutes*60,weekOf(epoch),start.slice(0,10));}
function book(db,id,slotId,packageId='essential'){db.prepare("INSERT INTO bookings(id,slot_id,package,name,email,status,created,expires,checkout_id,token_hash,token_cipher) VALUES(?,?,?,?,?,'held',?,?,?,?,?)").run(id,slotId,packageId,'Test Client','client@example.com',1790000000,1790002000,'cs_'+id,'hash_'+id,'encrypted');}
function session(id,packageId='essential'){return {id:'cs_'+id,metadata:{booking_id:id,kind:'deposit'},mode:'payment',status:'complete',payment_status:'paid',currency:'usd',amount_total:PACKAGES[packageId].deposit,livemode:false};}
test('package deposits and balances match totals',()=>{for(const p of Object.values(PACKAGES))assert.equal(p.deposit+p.balance,p.total);assert.equal(PACKAGES.essential.deposit,3000);assert.equal(PACKAGES.signature.deposit,4500);});
test('Chicago dates and DST are explicit',()=>{assert.equal(weekOf(chicagoEpoch('2027-01-10T18:00')),'2027-01-04');assert.throws(()=>chicagoEpoch('2026-11-01T01:30'));assert.throws(()=>chicagoEpoch('2027-03-14T02:30'));});
test('requires two distinct protected B4US blocks',()=>{const db=database();db.exec("INSERT INTO weeks VALUES('2027-01-04',6)");assert.throws(()=>slot(db,'s'));});
test('blocks overlapping B4US and travel buffers',()=>{const db=database();seed(db);assert.throws(()=>slot(db,'s','2027-01-04T11:00'));slot(db,'s');assert.throws(()=>slot(db,'s2','2027-01-06T13:15'));assert.throws(()=>db.prepare('INSERT INTO blocks VALUES(?,?,?,?,?)').run('security','security',chicagoEpoch('2027-01-06T11:45'),chicagoEpoch('2027-01-06T12:15'),'2027-01-04'));});
test('only one active reservation per appointment',()=>{const db=database();seed(db);slot(db,'s');book(db,'a','s');assert.throws(()=>book(db,'b','s'));});
test('weekly cap includes pending holds',()=>{const db=database();seed(db,1);slot(db,'s');slot(db,'s2','2027-01-07T12:00');book(db,'a','s');assert.throws(()=>book(db,'b','s2'));});
test('unpaid booking cannot become confirmed',()=>{const db=database();seed(db);slot(db,'s');book(db,'a','s');assert.throws(()=>db.exec("UPDATE bookings SET status='confirmed' WHERE id='a'"));});
test('consultation requires verified payment and intake, never more than 10 minutes',()=>{const db=database();seed(db);slot(db,'s','2027-01-08T12:00');slot(db,'c','2027-01-06T12:00','consult',10);book(db,'a','s');assert.throws(()=>db.exec("INSERT INTO consultations VALUES('a','c')"));db.exec("UPDATE bookings SET deposit_paid=1,status='confirmed' WHERE id='a'");assert.throws(()=>db.exec("INSERT INTO consultations VALUES('a','c')"));db.exec("UPDATE bookings SET intake='{}' WHERE id='a'; INSERT INTO consultations VALUES('a','c')");assert.equal(db.prepare('SELECT COUNT(*) n FROM consultations').get().n,1);});
test('payment verification rejects wrong amount, currency, mode, session, and unpaid status',()=>{const booking={id:'a',package:'essential',checkout_id:'cs_a'};const good=session('a');assert.ok(paidSessionMatches(good,booking,'deposit',false));for(const patch of [{amount_total:4500},{currency:'eur'},{livemode:true},{payment_status:'unpaid'},{status:'open'},{id:'cs_other'},{mode:'subscription'}])assert.equal(paidSessionMatches({...good,...patch},booking,'deposit',false),false);});
test('both paid packages confirm atomically; duplicate events do not duplicate emails',async()=>{for(const pkg of ['essential','signature']){const db=database();seed(db);slot(db,'s');book(db,'a','s',pkg);const env={DB:adapter(db),STRIPE_LIVE:'false'};await processPaid(env,session('a',pkg),'evt_1');await processPaid(env,session('a',pkg),'evt_1');await processPaid(env,session('a',pkg),'evt_2');assert.equal(db.prepare('SELECT status FROM bookings').get().status,'confirmed');assert.equal(db.prepare('SELECT COUNT(*) n FROM outbox').get().n,3);}});
test('failed/unpaid processing never confirms appointment',async()=>{const db=database();seed(db);slot(db,'s');book(db,'a','s');await assert.rejects(processPaid({DB:adapter(db),STRIPE_LIVE:'false'},{...session('a'),payment_status:'unpaid'},'evt_fail'));assert.equal(db.prepare('SELECT status FROM bookings').get().status,'held');});
test('expired reservation permits a new booking; canceled payment needs review',async()=>{const db=database();seed(db);slot(db,'s');book(db,'a','s');db.exec("UPDATE bookings SET status='expired' WHERE id='a'");book(db,'b','s');await processPaid({DB:adapter(db),STRIPE_LIVE:'false'},session('a'),'evt_late');assert.equal(db.prepare("SELECT status FROM bookings WHERE id='a'").get().status,'expired');assert.equal(db.prepare("SELECT kind FROM outbox").get().kind,'payment_review');});
test('closed appointments and short Signature slots reject reservations',()=>{const db=database();seed(db);slot(db,'s','2027-01-06T12:00','shoot',30);assert.throws(()=>book(db,'a','s','signature'));db.exec("UPDATE slots SET open=0 WHERE id='s'");assert.throws(()=>book(db,'b','s'));});
test('reschedule respects weekly cap and active appointment uniqueness',()=>{const db=database();seed(db,1);slot(db,'s');slot(db,'s2','2027-01-07T12:00');book(db,'a','s');db.exec("UPDATE bookings SET deposit_paid=1,status='confirmed' WHERE id='a'; UPDATE bookings SET slot_id='s2' WHERE id='a'");assert.equal(db.prepare('SELECT slot_id FROM bookings').get().slot_id,'s2');});
test('client tokens are encrypted at rest',async()=>{const encrypted=await cryptToken('private-token','test-only-encryption-key');assert.notEqual(encrypted,'private-token');assert.equal(await cryptToken(encrypted,'test-only-encryption-key',true),'private-token');await assert.rejects(cryptToken(encrypted,'wrong-key',true));assert.equal((await digest('token')).length,64);});
test('launch gate remains closed and private APIs require authorization',async()=>{const db=database();const env={DB:adapter(db),PAYMENTS_ENABLED:'false'};const availability=await handle(new Request('https://example.com/api/availability'),env);assert.deepEqual(await availability.json(),{paymentsEnabled:false,slots:[]});assert.equal((await handle(new Request('https://example.com/api/client'),env)).status,401);assert.equal((await handle(new Request('https://example.com/api/admin'),env)).status,503);assert.equal((await handle(new Request('https://example.com/api/bookings',{method:'POST',headers:{Origin:'https://example.com','Content-Type':'application/json'},body:'{}'}),env)).status,503);});
test('forged Stripe webhook signatures are rejected',async()=>{const db=database();const response=await handle(new Request('https://example.com/api/webhook',{method:'POST',headers:{'Stripe-Signature':'t=1,v1=forged'},body:'{}'}),{DB:adapter(db),STRIPE_SECRET_KEY:'sk_test_dummy_no_network',STRIPE_WEBHOOK_SECRET:'whsec_test_only',EXPECTED_STRIPE_ACCOUNT:'acct_test'});assert.equal(response.status,400);});

import {createHmac} from 'node:crypto';
import {maintenance} from '../src/operations.mjs';
test('genuine signed webhook verifies server state and rejects duplicate confirmation delivery',async()=>{
 const db=database();seed(db);slot(db,'s');book(db,'a','s');
 const original=globalThis.fetch;
 globalThis.fetch=async input=>{const url=new URL(typeof input==='string'?input:input.url||String(input));if(url.pathname==='/v1/account')return Response.json({id:'acct_blaze_test'});if(url.pathname==='/v1/checkout/sessions/cs_a')return Response.json(session('a'));throw new Error('Unexpected external call');};
 try{
 const payload=JSON.stringify({id:'evt_signed',type:'checkout.session.completed',livemode:false,data:{object:{id:'cs_a'}}});const t=Math.floor(Date.now()/1000);const signature=createHmac('sha256','whsec_local_fixture').update(t+'.'+payload).digest('hex');const env={DB:adapter(db),STRIPE_LIVE:'false',EXPECTED_STRIPE_ACCOUNT:'acct_blaze_test',STRIPE_SECRET_KEY:'sk_test_local_fixture',STRIPE_WEBHOOK_SECRET:'whsec_local_fixture'};
 for(let i=0;i<2;i++){const response=await handle(new Request('https://example.com/api/webhook',{method:'POST',headers:{'Stripe-Signature':`t=${t},v1=${signature}`},body:payload}),env);assert.equal(response.status,200);}
 assert.equal(db.prepare('SELECT status FROM bookings').get().status,'confirmed');assert.equal(db.prepare('SELECT COUNT(*) n FROM outbox').get().n,3);
 }finally{globalThis.fetch=original;}
});
test('email outbox sends the verified client link once and retains failed delivery',async()=>{
 const db=database();seed(db);slot(db,'s');book(db,'a','s');const encrypted=await cryptToken('a'.repeat(64),'local-encryption-fixture');db.prepare("UPDATE bookings SET deposit_paid=1,status='confirmed',token_cipher=? WHERE id='a'").run(encrypted);db.exec("INSERT INTO outbox(id,booking_id,kind,due) VALUES('message-1','a','confirmation',0)");
 const original=globalThis.fetch;const sent=[];globalThis.fetch=async (url,options)=>{assert.equal(url,'https://api.resend.com/emails');sent.push(JSON.parse(options.body));return Response.json({id:'test-message'});};
 const env={DB:adapter(db),RESEND_API_KEY:'local-email-fixture',TOKEN_ENCRYPTION_KEY:'local-encryption-fixture',SITE_URL:'https://example.com',EMAIL_FROM:'studio@example.com',CONTACT_EMAIL:'studio@example.com',ADMIN_EMAIL:'owner@example.com'};
 try{await maintenance(env);await maintenance(env);assert.equal(sent.length,1);assert.deepEqual(sent[0].to,['client@example.com']);assert.ok(sent[0].text.includes('/client.html#'+'a'.repeat(64)));assert.ok(sent[0].text.includes('$30'));db.exec("INSERT INTO outbox(id,booking_id,kind,due) VALUES('message-2','a','shoot_reminder',0)");globalThis.fetch=async()=>new Response('rejected',{status:503});await maintenance(env);const pending=db.prepare("SELECT sent,attempts FROM outbox WHERE id='message-2'").get();assert.equal(pending.sent,null);assert.equal(pending.attempts,1);}finally{globalThis.fetch=original;}
});
test('calendar closure cannot race an occupied reservation',()=>{const db=database();seed(db);slot(db,'s');book(db,'a','s');assert.throws(()=>db.exec("UPDATE slots SET open=0 WHERE id='s'"));assert.equal(db.prepare('SELECT open FROM slots').get().open,1);});
